apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-salutation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app-Salutation
  template:
    metadata:
      labels:
        app: spring-app-Salutation
    spec:
      containers:
      - name: spring-app-Salutation
        image: safa318/salutation:v1.0
        ports:
        - containerPort: 8888
