apiVersion: apps/v1
kind: Deployment
metadata:
  name: springappsalutation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springappsalutation
  template:
    metadata:
      labels:
        app: springappsalutation
    spec:
      containers:
      - name: spring-app-Salutation
        image: safa318/salutation:v1.0
        ports:
        - containerPort: 8888
